### ISSUE TITLE
Framework event handling

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#182]
We should re-implement Firefox's framework event handling for react and other libraries.

**Benefit**:
Mouse events are one of the first things that users want to do. It'll really help us in terms of onboarding new users.

**Comment by bhackett1024** [comment]
We now support showing React event listeners in the inspector.  This is done entirely in the client (https://github.com/WebReplay/webreplay-devtools/commit/6884c6f144993b1de679445f43fdc53e0340e345) by looking for react-specific properties attached to the node.  Since this is all client side it should be easy to handle listeners for other frameworks.

Next I'm going to look into showing calls to framework event listeners when event listener logpoints are turned on.

<img width="750" alt="Screen Shot 2020-07-14 at 10 07 58 AM" src="https://user-images.githubusercontent.com/1062578/87471695-7eca5680-c5ba-11ea-9eab-3c501b3cafdb.png">

**Comment by bhackett1024** [comment]
After some other fixes we can now show framework events when adding event logpoints (only handling React for now).  The screenshot below shows the logs from a click event: two react event handlers are called (a dummy event handler on the element itself, and the main event handler), and then the framework handler.

<img width="1158" alt="Screen Shot 2020-07-15 at 11 57 01 AM" src="https://user-images.githubusercontent.com/1062578/87602280-6b8aba00-c692-11ea-8bff-843eca45d1f4.png">
