### ISSUE TITLE
[inspector] populate RuleFront fields

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#199]
There are a couple fields missing in the RuleFront that would improve the rule view quite a bit

- isSystem
- inherited
- pseudoElement

Once we have this data, the rule view will sort better and the selectors will not appeared greyed out.

```js
diff --git a/src/protocol/thread.js b/src/protocol/thread.js
index 682561cc..679c9f57 100644
--- a/src/protocol/thread.js
+++ b/src/protocol/thread.js
@@ -943,6 +943,16 @@ RuleFront.prototype = {
     return this._rule.type;
   },

+  // data should be populated in the server similar to
+  // https://searchfox.org/mozilla-central/source/devtools/server/actors/styles.js#811-838
+  get isSystem() {},
+
+  get inherited() {},
+
+  get pseudoElement() {},
+
   get cssText() {
     return this._rule.cssText;
   },
```

**Comment by bhackett1024** [comment]
https://github.com/WebReplay/webreplay-devtools/commit/0acbcf2ad9f2f4769f10d377784c29df6e5720c4 adds StyleSheetFront.isSystem

**Comment by bhackett1024** [comment]
We can determine which rules come from the system now, but I have questions/concerns about the other two:

The plan I had in mind for dealing with inherited rules was to figure this out in the client.  It's not very specific to say whether a rule is inherited or not --- that just means it was applied to some parent node, and one or more of its styles was inherited by the node of interest.  Someone still has to do the work of figuring out which styles for the node are inherited from which rules, because InspectorUtils doesn't supply that for us.  It would be nice to do this in the client rather than the server, to keep the protocol simpler, reduce the amount of data that has to be downloaded to the client, and avoid having to reimplement this stuff in the server (we can pull in stuff from firefox like css-logic.js in webreplay-devtools, but not the backend).  I think that the protocol already provides enough information to figure this stuff out.  Does this approach make sense?

For pseudoElement, what are we looking for?  I don't see anything like this in the firefox devtools spec, and I don't know what it would refer to anyways because a rule can apply to multiple kinds of pseudo elements (or both pseudo and non-pseudo elements) depending on its selector.

**Comment by jasonLaster** [comment]
That makes sense. I prefer a simpler protocol as well.

It'll also be nice to have more code publicly available.

**Comment by bhackett1024** [comment]
The rules view now shows rules for pseudo elements and rules inherited from parent elements.  Rules are shown in priority order (specificity + order in style sheets), and the client is already able to use this ordering to figure out which declarations override each other.  This all ended up being pretty straightforward without requiring much new code, since the client already has most of the needed logic and providing rules in priority order is simple (InspectorUtils.getCSSStyleRules already does this).

<img width="354" alt="Screen Shot 2020-07-07 at 4 18 36 PM" src="https://user-images.githubusercontent.com/1062578/86866988-b6db1200-c06d-11ea-98f4-bff1ad9a5252.png">
