### ISSUE TITLE
[Debugger] map original scope names

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#204]
At the moment, the scope names are always "generated", which can be a bit confusing when debugging original code.

It would be nice if they were either generic names like "Block", "Lexical" or used the original names.

<img width="2254" alt="generated scope names" src="https://user-images.githubusercontent.com/254562/86535200-73c54700-be93-11ea-9c44-fb41e0a9b857.png">

#### STR:
1. go to https://webreplay.io/view?id=79f58428-6472-4e9d-a738-1f53902bdfef
2. pause in App.js:192

meta: #62

**Comment by bhackett1024** [comment]
When original names are present for functions, we use them now if possible.  Otherwise the function is anonymous.  Unfortunately, at this point in firebugs.dev all the in scope functions are shown as anonymous.  When we can switch to the generated source (will work on that tomorrow) I'll be able to investigate what's going on here.

**Comment by bhackett1024** [comment]
https://github.com/WebReplay/webreplay-devtools/commit/9198de392c1f8875046a2b69a0db776a7e6ba5ac

**Comment by bhackett1024** [comment]
There is now a button at the base of the source --- Switch to blahblah.js --- that switches things over to use the generated source and variable names.  Looking at this it's clear the packaging process converted the functions to anonymous ones, and spidermonkey picked names for those functions based on assorted non-mapped variables created by the packager.  So, it looks like we're doing about as well as we can do here with the renaming.  Switching back and forth to the generated source feels good to me, it's easy to see what happens when e.g. constructing the JSX elements in this function, but you will only see the generated source when you actually want to see it.
