### ISSUE TITLE
[Sourcemaps] mappings made it hard to fix continueToHere

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#227]
There were a couple of weird cases  that i encountered when debugging continueToHere

issues
- it looked like we entered a return that we didn't. [video 2]
- a variable was not defined [video 3] (1:20)
- stepping was difficult 

videos
- [video 1](https://www.loom.com/share/cefff35caff24e5297f7ea0e693626a3)
- [video 2](https://www.loom.com/share/76e5693040aa4a2a9899f9d43e342df9)
- [video 3](https://www.loom.com/share/a8949805a5874bb598372fb57f8f244f)

[video 2]: https://www.loom.com/share/76e5693040aa4a2a9899f9d43e342df9
[video 3]: https://www.loom.com/share/a8949805a5874bb598372fb57f8f244f

**Comment by jasonLaster** [comment]
To be fair, because these are source map issues, it might be impossible... but i think it is good to see if there's something we can do to make it slightly better...

**Comment by bhackett1024** [comment]
For the first issue, I adjusted how we deal with inexact source mappings so that we slide up to the next location instead of back to the previous one.  In this case we were trying to map the await after the return, which isn't in the source mapping.  This could of course make the mapping worse in other areas, but let's see if there's any fallout.

**Comment by bhackett1024** [comment]
For the second issue, I don't see what we can do to be able to evaluate the `columnBreakpoints` variable, because it was inlined entirely by webpack and doesn't match up with a variable in the generated source.

BTW, for finding places where exceptions are thrown like this, I find the "log exceptions" toggle to be very useful.  It might be nice to change the appearance of the frame timeline when the current frame throws an exception instead of terminating normally, to help with understanding the stepping.

**Comment by bhackett1024** [comment]
Is there anything about stepping that was difficult, other than the out of order execution when stepping in video 3?  That is a related thing to what webpack did, when it removed the columnBreakpoints variable it also reordered the statements such that we can step forward and go to an earlier original location.  As for the missing columnBreakpoints variable this is clearer when switching to the generated source, but I don't think there's anything more we can really do to improve the stepping experience here, as what we're doing best reflects what the generated source is doing, and is what the source maps tell us to do anyhow.

**Comment by bhackett1024** [comment]
I filed #253 for the bad error-clicking behavior in the first video (clicking on the error should take you straight to the problem).

**Comment by jasonLaster** [comment]
Thanks. I think that's ideal....

honestly, i mostly wanted to share some of these weird edge cases. it's
fine to ignore...

and some of these will be great bugs to webpack... like here's a recording
of how bad your stepping logic is!
